# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_building_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSwitches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_game', models.IntegerField(choices=[(0, '0'), (1, '1')], default=1)),
                ('end_game', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='status',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=1),
        ),
    ]
