# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170817_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Building',
            new_name='Buildings',
        ),
    ]
