# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20170817_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
