# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_userprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
