# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_userprofile_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0),
        ),
    ]
