# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='0000000000000000000000000', max_length=30),
        ),
    ]
