# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20170819_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='0000000000000000000000000', max_length=30),
        ),
    ]
