# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-20 06:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20170820_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email1',
            field=models.CharField(help_text='The email id should be in this format: f201xxxxx@pilani.bits-pilani.ac.in', max_length=34, validators=[django.core.validators.RegexValidator(re.compile('^f201[0-9]{4-5}@pilani\\.bits-pilani\\.ac\\.in$', 32), 'Enter yor valid BITS-mail', 'invalid!')]),
        ),
    ]
