# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-20 08:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20170820_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone2',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d{10}$', 32), code='Invalid!', message='Enter the valid phone number.')]),
        ),
    ]
