# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_userprofile_phone2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='q_skipped',
        ),
        migrations.RemoveField(
            model_name='building',
            name='q_solved',
        ),
        migrations.RemoveField(
            model_name='building',
            name='q_wrong',
        ),
    ]
