# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20170821_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='build_solved',
            field=models.CharField(default='00000000000000000000000000', max_length=30),
        ),
    ]
