# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_userprofile_build_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='build_solved',
        ),
    ]
