# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_userprofile_build_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wrong_responses',
            field=models.IntegerField(default=0),
        ),
    ]
