# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 05:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20170824_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skipped',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email1',
            field=models.CharField(help_text=b'The email id should be in this format: f201xxxxx@pilani.bits-pilani.ac.in', max_length=34, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^f201[0-9]{4,5}@pilani\\.bits-pilani\\.ac\\.in'), code=b'invalid!', message=b'Enter yor valid BITS-mail')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email2',
            field=models.CharField(blank=True, help_text=b'The email id should be in this format: f201xxxxx@pilani.bits-pilani.ac.in', max_length=34, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^f201[0-9]{4,5}@pilani\\.bits-pilani\\.ac\\.in'), code=b'invalid!', message=b'Enter yor valid BITS-mail')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='idno1',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile(b'^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P$'), code=b'invalid!', message=b'Enter your valid BITS-mail')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='idno2',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(re.compile(b'^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P$'), code=b'invalid!', message=b'Enter your valid BITS-mail')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone1',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile(b'^\\d{10}$'), code=b'Invalid!', message=b'Enter the valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone2',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.RegexValidator(re.compile(b'^\\d{10}$'), code=b'Invalid!', message=b'Enter the valid phone number.')]),
        ),
    ]
