# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 13:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20170827_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone2',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='idno1',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P$', 32), code='invalid!', message='Enter your valid BITS-mail')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='idno2',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(re.compile('^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P$', 32), code='invalid!', message='Enter your valid BITS-mail')]),
        ),
    ]
