# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20170828_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logstat',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=0),
        ),
    ]
