# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20170910_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='build_solved',
            new_name='attempts',
        ),
    ]
