# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 19:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20170911_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sprite',
            field=models.CharField(choices=[('girl', 'girl'), ('boy', 'boy')], default='girl', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='idno2',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(re.compile('^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P$', 32), code='invalid!', message='Enter your valid BITS-mail')]),
        ),
    ]
