# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20170912_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bstat',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000', max_length=80),
        ),
    ]
