# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20170912_1802'),
        ('mainapp', '0040_auto_20170912_1231'),
    ]

    operations = [
    ]
