# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20170913_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='context',
        ),
        migrations.AddField(
            model_name='answer',
            name='Answer',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
