# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_auto_20170913_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Answer',
            field=models.CharField(default='ah', max_length=100),
        ),
    ]
