# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_auto_20170913_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Answer',
            new_name='answer',
        ),
    ]
