# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 17:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20170913_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('teamname', models.CharField(max_length=200)),
                ('idno1', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P$', 32), code='invalid!', message='Enter your valid BITS-mail')])),
            ],
        ),
    ]
